version: '3.8'

services:
  app:
    build: .
    container_name: dash-app
    restart: unless-stopped
    ports:
      - "3485:80"  # Aplikasi akan berjalan di port 3485 dan diakses melalui reverse proxy

networks:
  default:
    driver: bridge